[2022-07-26 13:07:56,231] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: our_first_dag.task2 manual__2022-07-26T13:07:54.085594+00:00 [queued]>
[2022-07-26 13:07:56,277] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: our_first_dag.task2 manual__2022-07-26T13:07:54.085594+00:00 [queued]>
[2022-07-26 13:07:56,277] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-07-26 13:07:56,278] {taskinstance.py:1377} INFO - Starting attempt 1 of 6
[2022-07-26 13:07:56,279] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-07-26 13:07:56,315] {taskinstance.py:1397} INFO - Executing <Task(BashOperator): task2> on 2022-07-26 13:07:54.085594+00:00
[2022-07-26 13:07:56,326] {standard_task_runner.py:52} INFO - Started process 5839 to run task
[2022-07-26 13:07:56,360] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'our_first_dag', 'task2', 'manual__2022-07-26T13:07:54.085594+00:00', '--job-id', '129', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmppmrcx85u', '--error-file', '/tmp/tmpd7mwbv0w']
[2022-07-26 13:07:56,369] {standard_task_runner.py:80} INFO - Job 129: Subtask task2
[2022-07-26 13:07:56,882] {task_command.py:371} INFO - Running <TaskInstance: our_first_dag.task2 manual__2022-07-26T13:07:54.085594+00:00 [running]> on host 24820bb59fd1
[2022-07-26 13:07:57,114] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=coder2j
AIRFLOW_CTX_DAG_ID=our_first_dag
AIRFLOW_CTX_TASK_ID=task2
AIRFLOW_CTX_EXECUTION_DATE=2022-07-26T13:07:54.085594+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-07-26T13:07:54.085594+00:00
[2022-07-26 13:07:57,117] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-07-26 13:07:57,124] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'echo , second task']
[2022-07-26 13:07:57,143] {subprocess.py:85} INFO - Output:
[2022-07-26 13:07:57,146] {subprocess.py:92} INFO - , second task
[2022-07-26 13:07:57,148] {subprocess.py:96} INFO - Command exited with return code 0
[2022-07-26 13:07:57,260] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=our_first_dag, task_id=task2, execution_date=20220726T130754, start_date=20220726T130756, end_date=20220726T130757
[2022-07-26 13:07:57,348] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-07-26 13:07:57,511] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
