[2022-07-26 13:11:00,812] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: our_first_dag.task2 manual__2022-07-26T13:08:58.356560+00:00 [queued]>
[2022-07-26 13:11:00,828] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: our_first_dag.task2 manual__2022-07-26T13:08:58.356560+00:00 [queued]>
[2022-07-26 13:11:00,829] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-07-26 13:11:00,830] {taskinstance.py:1377} INFO - Starting attempt 2 of 6
[2022-07-26 13:11:00,830] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-07-26 13:11:00,851] {taskinstance.py:1397} INFO - Executing <Task(BashOperator): task2> on 2022-07-26 13:08:58.356560+00:00
[2022-07-26 13:11:00,858] {standard_task_runner.py:52} INFO - Started process 6028 to run task
[2022-07-26 13:11:00,862] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'our_first_dag', 'task2', 'manual__2022-07-26T13:08:58.356560+00:00', '--job-id', '134', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmpujyja9sz', '--error-file', '/tmp/tmpkk3nt6_5']
[2022-07-26 13:11:00,864] {standard_task_runner.py:80} INFO - Job 134: Subtask task2
[2022-07-26 13:11:00,939] {task_command.py:371} INFO - Running <TaskInstance: our_first_dag.task2 manual__2022-07-26T13:08:58.356560+00:00 [running]> on host 24820bb59fd1
[2022-07-26 13:11:01,027] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=coder2j
AIRFLOW_CTX_DAG_ID=our_first_dag
AIRFLOW_CTX_TASK_ID=task2
AIRFLOW_CTX_EXECUTION_DATE=2022-07-26T13:08:58.356560+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-07-26T13:08:58.356560+00:00
[2022-07-26 13:11:01,030] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-07-26 13:11:01,033] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'echo , second task']
[2022-07-26 13:11:01,046] {subprocess.py:85} INFO - Output:
[2022-07-26 13:11:01,048] {subprocess.py:92} INFO - , second task
[2022-07-26 13:11:01,049] {subprocess.py:96} INFO - Command exited with return code 0
[2022-07-26 13:11:01,090] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=our_first_dag, task_id=task2, execution_date=20220726T130858, start_date=20220726T131100, end_date=20220726T131101
[2022-07-26 13:11:01,116] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-07-26 13:11:01,176] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
